### ISSUE TITLE
Port Utilisation

### ISSUE THREAD

**Issue by emmhaych** [christianrauch/ros-multiwii#5]
This issue impacts both this project as well as it's [msp](https://github.com/christianrauch/msp) dependency.

Would be interested in a port utilisation metric that indicated the upload and download rate as a %, similar to how cleanflight displays it:
![image](https://user-images.githubusercontent.com/3681848/37247571-063bec86-24b5-11e8-9d87-bd1555762477.png)

I am happy to implement it but wanted to discuss the design considerations before proceeding. I was planning to:

- Add 2 new variables in [SerialPortImpl](https://github.com/christianrauch/msp/blob/master/src/SerialPortImpl.cpp#L3-L9) structure called `bytesDownloaded` and `bytesUploaded`
- Instrument [MSP::receiveData()](https://github.com/christianrauch/msp/blob/master/src/MSP.cpp#L204-L247) to add the number of bytes received to `bytesDownloaded`. This will be done by adding 3 bytes for MSP header, 2 bytes for `data_size` and MSP `id`, the data size (equals data length value) and 1 byte for CRC. 
_Could also do this in [`MSP::read()`](https://github.com/christianrauch/ros-multiwii/blob/master/src/multiwii_node.cpp#L503) if you recommend it_
- Instrument [MSP::sendData()](https://github.com/christianrauch/msp/blob/master/src/MSP.cpp#L189-L202) to add the number of bytes sent to `bytesUploaded`. This value will be `msg.size()`. 
_Could also do this in [`MSP::write()`](https://github.com/christianrauch/msp/blob/master/src/MSP.cpp#L258) if you recommend it_
- Add a new functions to [MSP.cpp](https://github.com/christianrauch/msp/blob/master/src/MSP.cpp) called `getTxBytes()` and `getRxBytes()`. These return the byte values and reset the counter to 0.
- Add 2 new functions to [FlightController.cpp](https://github.com/christianrauch/msp/blob/master/src/FlightController.cpp) called `getTxBytes()` and `getRxBytes()` which invoke the `client.getTxBytes()` and `client.getRxBytes()` calls and return the respective values.
- Implement `ros::Rate` class and poll the `fcu` every second, calculate the rates based on the data and transmit onto topic `/port_utilisation`

Looks like a simple and useful feature. Let me know if interested.

**Comment by christianrauch** [comment]
That sounds like a great idea and a useful feature. You want to measure the used bandwidth (in bytes/second) relative to the serial connected speed?
The ROS node is using the `FlightController` class, which in turn is using the `Client` class. The `MSP` class is actually not used for the ROS node.

I think the best place for the bandwidth feature would be in the `Client` class. For synchronous read and write operations, you could simply take the transferred bytes of `asio::write` and `asio::read` and measure the time it takes. You probably will need a moving average over these values.

Do you know how it's done in the Cleanflight or Betaflight GUI? We could get some inspiration from there.

**Comment by emmhaych** [comment]
Ah... I missed out the most important part of the calculation. You're right. The % will be calculated as a ratio of tx/rx bytes against the bitrate value.

Cleanflight configurator seems to be doing it in the same way: https://github.com/cleanflight/cleanflight-configurator/blob/master/src/js/port_usage.js. The only difference is that they don't reset the counters to 0 every second.

**Comment by christianrauch** [comment]
Since measuring the serial device bandwidth is quite a generic task, I was wondering if there isn't an application agnostic solution for Linux to measure the upstream and downstream bandwidth of any serial device.
There are tools to intercept the serial traffic:

- https://unix.stackexchange.com/questions/12359/how-can-i-monitor-serial-port-traffic
- https://stackoverflow.com/questions/940374/how-can-i-monitor-data-on-a-serial-port-in-linux
- https://serverfault.com/questions/112957/sniff-serial-port-on-linux

Do you think you could use one of those tools to measure the up/down bandwidth? E.g. instead of printing the transferred values, we only measure how many bytes are transferred in each direction of time.
I think this would be a better and more accurate solution than implementing this feature for each read/write operation in the driver.

**Comment by christianrauch** [comment]
Are you still interested in working on this? Have you had a look at the alternatives?
