### ISSUE TITLE
Arming service argument 

### ISSUE THREAD

**Issue by shlapion** [christianrauch/ros-multiwii#7]
Greetings, 

first of all thank you for sharing your code :)

Went through it and was wondering what argument does the `arming` service take?

According to the code the `res` and `req` are both of type `uint8_t` so should the service be called with an `int`?

**Comment by christianrauch** [comment]
Are you refering to the ROS service `cmd/arming`? It uses the service `mavros_msgs/CommandBool` that is defined at: http://docs.ros.org/hydro/api/mavros/html/srv/CommandBool.html. `value` is of type bool, and needs to be set to true (1) to arm the FC, and false (0) to disarm the FC.

**Comment by shlapion** [comment]
Thx for the info,

yes, I was reffering to the service `cmd/arming`. I tryed to call the service with the above mentioned bool value, however it does not arm. 

I am using a Matek F405 OSD running the newest version of iNav. Everything else works great. 

Do you by any chance have any experience running your node on any version of iNav?

**Comment by christianrauch** [comment]
I have note used iNav before. I only tested the node with MultiWii and Betaflight.
- Does the arming work with the GUI that comes with iNav?
- Do the example programs from the `msp` library (https://github.com/christianrauch/msp) work?

Reasons that otherwise prevent arming can be that your FC is not planar to the ground, in which case you will not be able to arm via the GUI. Alternative, you should always be able to arm the FC via the stick combination. The arming service in the ROS node (and the function in the library) send these stick combinations to the FC, there is no dedicated arming MSP message yet.

- Can you arm the FC via the RC stick combination? If yes, is it the same that is defined in the `msp` library?

**Comment by shlapion** [comment]
I have not taken a look at the examples from the MSP library yet. Will do so immidiately. 

The FC does arm, using the RC. Made sure that the FC is leveled, battery is charged and that communication with GPS sattelites is established. 
I have configured iNav to arm using on of the switches of the RC.  From the sound of it it looks like this could be at the root of the problem.

**Comment by shlapion** [comment]
I have taken a look at the examples form the MSP library and indeed the arming combination was different than what I have set up for my FC. 

However the FC does not arm. Maybe I am missing something obvious. Will give a short list of thing I have tried thus far, and maybe you can spot the error. 

1. Read the values  sent by the RC to the FC once disarmed and once armed. Store it in a file. 

2. Read the values form the file and,  set the them  in the  `arm` function located in `FlightController.cpp`

```
 bool FlightController::arm(const bool arm) {
    // arm:
    // ch 5 = 1520
    // disarm:
    // ch 5 = 1120
    
    return setRc(1500, 1501, 1500, 1005, 1520, 1520, 1520, 1940, 1520, 1940, 1520, 1520, 1520, 1520, 1520, 1520, 988, 988);
}
```
 

3. Save and compile. 

4. Launch the ROS Node
5. Call the service 'cmd/arming' with argument `true`. 

Test steps:

1. Place quad flat, connect battery wait for GPS Lock 
2. Arm using RC
3. Turn off RC and start the ROS node --> call service `cmd/arming`


Thx :)

**Comment by christianrauch** [comment]
Does the arming work with the iNav GUI? Since the FC arms via RC, what are the channels and the values for arming and disarming the FC? Can you also check the frequency which the values are sent to the FC? If there is a high delay in between sending these RC packages, the FC might go into failsafe mode.

**Comment by shlapion** [comment]
I don't think you can arm through the iNav GUI. 
The channel for arming/disarming is CH5 , while the value for arming is 1520 and for disarming is 1120. 
I am pretty sure the FC goes into failsafe mode after I  try to arm the FC by calling the `cmd/arming` service. (FC does not respond anymore and I can't send or receive any messages.). 

This issue however only occurs when I call the `arm_block` function. If I call the `arm` function directly I get a success message , however the FC still won't arm. I also casted the values sent through the channels form `int` to `uint16_t`. 

Could you point out how i could check/modify the frequency of the values sent to the FC?
I know for `rostopics` you can use the `rostpoic hz` commnad, but i searched and could not find any similar functionality for `rosservices`

As a second question, where does the 'rc/in' topic receive it's values? If the RC is not turened on shouldn't the values of `rc/in` be the same as set by the function `setRc`

**Comment by christianrauch** [comment]
Is it CH5 < 1120 for disarming and CH5 > 1520 for arming?
The frequency at which `MSP_RC` messages are sent from the ROS node to the FC depend on how frequent they are send to the ROS node. The node subscribes to topics `rc/override` (applies channel mapping as per setting) and `rc/override/raw` (applies no channel mapping) for RC control:
https://github.com/christianrauch/ros-multiwii/blob/b638584c178450c5996d563057f49aca77e62647/src/multiwii_node.cpp#L165-L166

You need to publish on one of these topics frequent enough to not trigger the failsafe mode. The minimum frequency depends on your failsafe settings (i.e. 1/failsafe_time). With `rostpoic hz` you can check how frequent you are publishing.

I used [multiwii_rc_joystick](https://github.com/christianrauch/multiwii_rc_joystick/blob/master/src/rc_joystick_node.cpp) with a gamepad to send messages to the ROS node. It's a node that reads from a USB device (gamepad or joystick) and sends ROS messages of type [`mavros_msgs/OverrideRCIn`](http://docs.ros.org/kinetic/api/mavros_msgs/html/msg/OverrideRCIn.html) to `rc/override/raw`. You can use it as a basis to format your own `OverrideRCIn` messages and send them to the MultiWii ROS node.

**Comment by shlapion** [comment]
Sorry for the late reply, I was out of the lab for a few days. 

The range for CH5 for arming is: Armed if between 1300 and 1700, Disarmed otherwise. 

Looked into the publishing rate and madam the according adjustments. Now the FC does not go into failsafe mode anymore. 
However arming still does not work. I suspect the issue lies with some of the iNav settings.

**Comment by christianrauch** [comment]
Does the FC im general not respond to RC commands send via MSP? Could you try to send RC values via the GUI, like it can be achieved with betaflight/cleanflight? You need to make sure that the MSP_RC messages that are sent to the FC are actually processed. At least in some firmware configurations of betaflight MSP_RC messaves are deactivated for some FC hardware boards.
